import type { Metric, TemperatureUnit } from '../types/heat-data';

export type Language = 'en' | 'es';
type TextKey = keyof typeof translations.en;
const translations = {
  en: { title:'Puerto Rico Heat Atlas', metadataDescription:'Explore historical hot days, warm nights, heat streaks, and temperature trends across Puerto Rico using NOAA/NCEI weather-station observations.', subtitle:'Historical temperature, hot-day frequency, and nighttime heat across Puerto Rico.', units:'Units', language:'Language', about:'About the data', share:'Share', searchLabel:'Find a station', searchPlaceholder:'Search stations', selectedStation:'Selected station', mapMetric:'Map metric', selectedYear:'Selected year', year:'Year', play:'Play', pause:'Pause', reset:'Reset map view', history:'History at this station', coverage:'stations reporting', noStation:'No station selected', loadingStation:'Loading station…', linkCopied:'Link copied', copyFailed:'Could not copy the link. Copy this page URL from your browser.', loadingStations:'Loading station data…', loadingBoundary:'Loading Puerto Rico boundary…', boundaryFailed:'The Puerto Rico boundary could not be loaded. You can still use the map.', stationsFailed:'Station data could not be loaded. Please try again later.', retry:'Retry', noData:'No data is available for this station and selection.', noChart:'No historical data is available for this metric.', periodChart:'Historical chart is not available for period-change metrics.', period:'2006–2025 vs 1961–1980', dataCoverage:'Data coverage', historicalContext:'Historical context', observedDays:'Observed days', aboutTitle:'About the data', close:'Close', source:'Source: NOAA/NCEI daily historical observations · Data completeness describes observation coverage only.', limitation:'Temperature-only historical data. Not official heat index or WBGT.', details:'Source details', generated:'Dataset generated from the project data refresh.', metricDefinitions:'Metric definitions', methodology:'What this atlas shows', aboutBody:'This atlas summarizes historical daily temperature observations from NOAA/NCEI stations in Puerto Rico. It is temperature-only: it is not official heat index, WBGT, an official feels-like temperature, or a medical-risk category.', baseline:'The 1991–2020 baseline is used for available anomaly context. Percentiles show how a valid year compares with other valid years at the same station. Coverage labels describe observational coverage only; the current year may be incomplete.', attribution:'Originally developed as a graduate project. NOAA/NCEI is the source for the historical daily observations.', results:'station results' },
  es: { title:'Atlas de Calor de Puerto Rico', metadataDescription:'Explore días calurosos, noches cálidas, rachas de calor y tendencias históricas de temperatura en Puerto Rico con observaciones de estaciones meteorológicas de NOAA/NCEI.', subtitle:'Temperatura histórica, frecuencia de días calurosos y calor nocturno en Puerto Rico.', units:'Unidades', language:'Idioma', about:'Acerca de los datos', share:'Compartir', searchLabel:'Buscar una estación', searchPlaceholder:'Buscar estaciones', selectedStation:'Estación seleccionada', mapMetric:'Métrica del mapa', selectedYear:'Año seleccionado', year:'Año', play:'Reproducir', pause:'Pausar', reset:'Restablecer vista del mapa', history:'Historial en esta estación', coverage:'estaciones reportando', noStation:'No se seleccionó una estación', loadingStation:'Cargando estación…', linkCopied:'Enlace copiado', copyFailed:'No se pudo copiar el enlace. Copie la URL de esta página desde su navegador.', loadingStations:'Cargando datos de estaciones…', loadingBoundary:'Cargando límite de Puerto Rico…', boundaryFailed:'No se pudo cargar el límite de Puerto Rico. Aún puede usar el mapa.', stationsFailed:'No se pudieron cargar los datos de estaciones. Inténtelo de nuevo más tarde.', retry:'Reintentar', noData:'No hay datos disponibles para esta estación y selección.', noChart:'No hay datos históricos disponibles para esta métrica.', periodChart:'El gráfico histórico no está disponible para métricas de cambio entre períodos.', period:'2006–2025 frente a 1961–1980', dataCoverage:'Cobertura de datos', historicalContext:'Contexto histórico', observedDays:'Días observados', aboutTitle:'Acerca de los datos', close:'Cerrar', source:'Fuente: observaciones históricas diarias de NOAA/NCEI · La completitud de datos describe solo la cobertura observacional.', limitation:'Datos históricos de temperatura únicamente. No es índice de calor oficial ni WBGT.', details:'Detalles de la fuente', generated:'Conjunto de datos generado mediante la actualización de datos del proyecto.', metricDefinitions:'Definiciones de métricas', methodology:'Qué muestra este atlas', aboutBody:'Este atlas resume observaciones históricas diarias de temperatura de estaciones NOAA/NCEI en Puerto Rico. Es solo de temperatura: no es índice de calor oficial, WBGT, temperatura oficial de sensación térmica ni categoría de riesgo médico.', baseline:'El período base 1991–2020 se usa para el contexto de anomalías cuando está disponible. Los percentiles muestran cómo se compara un año válido con otros años válidos en la misma estación. Las etiquetas de cobertura describen solo la cobertura observacional; el año actual puede estar incompleto.', attribution:'Desarrollado originalmente como proyecto de posgrado. NOAA/NCEI es la fuente de las observaciones históricas diarias.', results:'resultados de estaciones' }
} as const;

export function t(language: Language, key: TextKey): string { return translations[language][key]; }
export function metricText(metric: Metric, unit: TemperatureUnit, language: Language): string {
  const degrees = unit === 'F' ? { hot:90, very:95, night:75 } : { hot:32, very:35, night:24 };
  const labels: Record<Language, Record<Metric, string>> = {
    en: { hot_days_32:`Hot days (Tmax ≥ ${degrees.hot} °${unit})`, hot_days_35:`Very hot days (Tmax ≥ ${degrees.very} °${unit})`, warm_nights_24:`Warm nights (Tmin ≥ ${degrees.night} °${unit})`, oppressive_days:`Oppressive days (Tmax ≥ ${degrees.hot} °${unit} & Tmin ≥ ${degrees.night} °${unit})`, delta_hot_days_32:'Change in hot days (late − early)', delta_warm_nights_24:'Change in warm nights (late − early)' },
    es: { hot_days_32:`Días calurosos (Tmax ≥ ${degrees.hot} °${unit})`, hot_days_35:`Días muy calurosos (Tmax ≥ ${degrees.very} °${unit})`, warm_nights_24:`Noches cálidas (Tmin ≥ ${degrees.night} °${unit})`, oppressive_days:`Días opresivos (Tmax ≥ ${degrees.hot} °${unit} y Tmin ≥ ${degrees.night} °${unit})`, delta_hot_days_32:'Cambio en días calurosos (reciente − temprano)', delta_warm_nights_24:'Cambio en noches cálidas (reciente − temprano)' }
  };
  return labels[language][metric];
}
