import 'leaflet/dist/leaflet.css';
import './styles/main.css';
import * as L from 'leaflet';
import { Chart, type ChartConfiguration } from 'chart.js/auto';
import boundaryUrl from '../data/pr_boundary.geojson?url';
import stationsUrl from '../data/stations_heatmetrics_all.geojson?url';
import { fetchJson, parseBoundary, parseStations } from './data/load-data';
import type { AppState, Metric, StationFeature, TemperatureUnit } from './types/heat-data';
import { collectAvailableYears, completenessLabel, coverage, daysInYear, formatCompleteness, isDeltaMetric, markerColor, metricDefinition, metricPercentile, metricValue, selectedStation, summaryFor, valueFor } from './utils/metrics';
import { friendlyStationName, searchStations } from './utils/stations';
import { metricText, t, type Language } from './utils/i18n';
import { parseUrlState, serializeUrlState } from './utils/url-state';

const center: L.LatLngExpression = [18.2208, -66.5901];
const state: AppState & { language: Language } = { year:null, metric:'hot_days_32', unit:'F', language:'en', playing:false, years:[], stations:null, selectedStation:null };
const map = L.map('map', { center, zoom:9, zoomControl:false }); L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
let stationLayer:L.GeoJSON|null=null, boundaryLayer:L.GeoJSON|null=null, timer:ReturnType<typeof setInterval>|null=null, chart:Chart|null=null, activeResult=-1;
const $=<T extends HTMLElement>(s:string):T=>document.querySelector<T>(s)!;
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string):HTMLElementTagNameMap[K]=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function say(message:string):void { $('#liveRegion').textContent=''; setTimeout(()=>$('#liveRegion').textContent=message,20); }
function setStatus(message='',kind='info', retry=false):void { const node=$('#appStatus'); node.replaceChildren();node.className=`status ${kind}`;if(message)node.append(document.createTextNode(message));if(retry){const b=el('button',t(state.language,'retry'));b.onclick=()=>void initialize();node.append(b);} if(message)say(message); }
function displayMetric():string{return metricText(state.metric,state.unit,state.language);}
function syncUrl():void { history.replaceState(null,'',`${location.pathname}?${serializeUrlState({stationId:state.selectedStation?.properties.id??null,year:state.year,metric:state.metric,unit:state.unit,language:state.language})}`); }
function metricDescription():string { return state.language==='es' ? metricDefinition(state.metric,state.unit).replace('Days with a high temperature of at least','Días con temperatura máxima de al menos').replace('Nights with a low temperature at or above','Noches con temperatura mínima de al menos').replace('Project-defined temperature proxy:','Proxy de temperatura definido por el proyecto:').replace('Difference between the','Diferencia entre los conteos promedio anuales de').replace('average annual counts.','.') : metricDefinition(state.metric,state.unit); }
function updateText():void { document.documentElement.lang=state.language;document.title=`${t(state.language,'title')} | ${state.language==='es'?'Métricas históricas de calor por estación':'Historical Station Heat Metrics'}`;const description=t(state.language,'metadataDescription');(['metaDescription','ogDescription','twitterDescription'] as const).forEach(id=>$('#'+id).setAttribute('content',description));$('#twitterTitle').setAttribute('content',t(state.language,'title'));
  const text:Record<string,string>={siteTitle:t(state.language,'title'),subtitle:t(state.language,'subtitle'),languageLabel:t(state.language,'language'),unitsLabel:t(state.language,'units'),shareBtn:t(state.language,'share'),aboutBtn:t(state.language,'about'),limitation:t(state.language,'limitation'),searchLabel:t(state.language,'searchLabel'),selectedStationLabel:t(state.language,'selectedStation'),sourceDetails:t(state.language,'details'),historyHeading:t(state.language,'history'),metricLabel:t(state.language,'mapMetric'),selectedYearLabel:t(state.language,'selectedYear'),yearInputLabel:t(state.language,'year'),resetMap:t(state.language,'reset'),footerText:t(state.language,'source'),aboutTitle:t(state.language,'aboutTitle'),methodologyHeading:t(state.language,'methodology'),definitionsHeading:t(state.language,'metricDefinitions'),aboutBody:t(state.language,'aboutBody'),baselineText:t(state.language,'baseline'),generatedText:t(state.language,'generated'),attributionText:t(state.language,'attribution')};
  Object.entries(text).forEach(([id,value])=>$('#'+id).textContent=value); $('#stationSearch').setAttribute('placeholder',t(state.language,'searchPlaceholder')); $('#languageSelect').setAttribute('aria-label',t(state.language,'language')); $('#unitSelect').setAttribute('aria-label',t(state.language,'units')); $('#closeAbout').setAttribute('aria-label',t(state.language,'close')); $('#aboutMetrics').replaceChildren(...(['hot_days_32','hot_days_35','warm_nights_24','oppressive_days'] as Metric[]).map(m=>el('li',metricText(m,state.unit,state.language)))); }
function updateSelectLabels():void { const select=$('#metricSelect') as HTMLSelectElement;[...select.options].forEach(o=>o.textContent=metricText(o.value as Metric,state.unit,state.language));select.value=state.metric;$('#metricDefinition').textContent=metricDescription(); }
function updateLegend():void { const root=$('#legend');root.replaceChildren(el('strong',displayMetric()));const labels=state.language==='es'?['Menos de 30','30–59','60–89','90–119','120 o más']:['Under 30','30–59','60–89','90–119','120 or more'];const colors=['#4575b4','#91bfdb','#fee090','#fdae61','#d73027'];labels.forEach((label,i)=>{const row=el('span');const dot=el('i');dot.style.backgroundColor=colors[i]!;row.append(dot,document.createTextNode(label));root.append(row);}); }
function updateTimeline():void { const range=$('#timeRange') as HTMLInputElement, delta=isDeltaMetric(state.metric);range.disabled=delta;$('#yearLabel').textContent=delta?t(state.language,'period'):state.year??'—';const play=$('#playPauseBtn') as HTMLButtonElement;play.disabled=delta||!state.years.length;play.textContent=state.playing?t(state.language,'pause'):t(state.language,'play');const data=state.stations?coverage(state.stations.features,state.metric,state.year):{withData:0,total:0};$('#coverageLabel').textContent=`${data.withData} ${state.language==='es'?'de':'of'} ${data.total} ${t(state.language,'coverage')}`; }
function updateChart(feature:StationFeature|null):void { chart?.destroy();chart=null;const canvas=$('#historyChart') as HTMLCanvasElement,empty=$('#chartEmpty');if(!feature||isDeltaMetric(state.metric)){canvas.hidden=true;empty.hidden=false;empty.textContent=t(state.language,'periodChart');return;}const values=feature.properties.metrics[state.metric]??{},years=state.years.filter(y=>values[y]!=null);if(!years.length){canvas.hidden=true;empty.hidden=false;empty.textContent=t(state.language,'noChart');return;}canvas.hidden=false;empty.hidden=true;const config:ChartConfiguration<'line',number[],string>={type:'line',data:{labels:years,datasets:[{label:displayMetric(),data:years.map(y=>values[y]??0),borderColor:'#c7512a',backgroundColor:'rgba(199,81,42,.12)',fill:true,tension:.25,pointRadius:years.map(y=>y===state.year?4:0),pointBackgroundColor:'#17324d',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.parsed.y} ${state.language==='es'?'días':'days'}`}}},scales:{x:{ticks:{maxTicksLimit:6,color:'#536271'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#536271'}}}}};chart=new Chart(canvas,config); }
function card(label:string,value:string,detail?:string):HTMLElement{const n=el('article');n.className='metric-card';n.append(el('h3',label),el('strong',value));if(detail)n.append(el('p',detail));return n;}
function updatePanel():void { const f=state.selectedStation,cards=$('#metricCards'),narrative=$('#narrative'),noData=$('#noData');cards.replaceChildren();narrative.replaceChildren();if(!f){$('#stationName').textContent=t(state.language,'noStation');$('#stationMeta').textContent='';$('#stationOfficial').textContent='';noData.hidden=false;noData.textContent=t(state.language,'noData');updateChart(null);return;}const p=f.properties,year=state.year, selected=metricValue(f,state.metric,year);$('#stationName').textContent=friendlyStationName(f);$('#stationMeta').textContent=`${year??t(state.language,'period')} · ${p.data_start_year??'—'}–${p.data_end_year??'—'}`;$('#stationOfficial').textContent=`${p.name} · ${p.id}`;noData.hidden=selected!==null;noData.textContent=t(state.language,'noData');const valid=valueFor(f,'valid_days',year),complete=valueFor(f,'completeness_pct',year),hot=valueFor(f,'hot_days_32',year),warm=valueFor(f,'warm_nights_24',year);cards.append(card(metricText('hot_days_32',state.unit,state.language),hot===null?'—':String(Math.round(hot))),card(metricText('warm_nights_24',state.unit,state.language),warm===null?'—':String(Math.round(warm))),card(state.language==='es'?'Racha calurosa más larga':'Longest hot streak',valueFor(f,'longest_hot_streak',year)===null?'—':String(valueFor(f,'longest_hot_streak',year))),card(t(state.language,'dataCoverage'),valid===null?'—':`${Math.round(valid)} / ${daysInYear(year)}`,complete===null?undefined:`${formatCompleteness(complete)} · ${completenessLabel(complete)}`));for(const line of summaryFor(f,state.metric,year,state.unit))narrative.append(el('p',line));const percentile=metricPercentile(f,state.metric,year);if(percentile!==null)cards.append(card(t(state.language,'historicalContext'),`${Math.round(percentile)}${state.language==='es'?'º':'th'} percentile`));updateChart(f); }
function redraw():void { if(!stationLayer||!state.stations)return;stationLayer.clearLayers();stationLayer.addData(state.stations as GeoJSON.GeoJsonObject); }
function updateAll(url=true):void { updateText();updateSelectLabels();updateLegend();updateTimeline();updatePanel();redraw();if(url)syncUrl(); }
function createStationLayer():L.GeoJSON{return L.geoJSON(null,{filter:r=>metricValue(r as StationFeature,state.metric,state.year)!==null,pointToLayer:(r,ll)=>{const f=r as StationFeature,chosen=f.properties.id===state.selectedStation?.properties.id;return L.circleMarker(ll,{radius:chosen?9:6,color:chosen?'#17324d':'#fff',weight:chosen?3:1.5,fillColor:markerColor(metricValue(f,state.metric,state.year),state.metric),fillOpacity:.95});},onEachFeature:(r,l)=>{const f=r as StationFeature;l.bindTooltip(`${friendlyStationName(f)} · ${metricValue(f,state.metric,state.year)??'—'}`,{direction:'top'});l.on('click',()=>choose(f));}});}
function choose(feature:StationFeature):void {state.selectedStation=feature;updateAll();say(`${t(state.language,'selectedStation')}: ${friendlyStationName(feature)}`);}
function stop():void{if(timer)clearInterval(timer);timer=null;state.playing=false;updateTimeline();}
function advance():void{const i=state.years.indexOf(state.year??state.years[0]!);state.year=state.years[(i+1)%state.years.length]??null;($('#timeRange') as HTMLInputElement).value=String(state.years.indexOf(state.year!));if(state.stations)state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id??null,state.metric,state.year);updateAll();}
function renderResults():void{const input=$('#stationSearch') as HTMLInputElement,list=$('#searchResults');if(!state.stations){list.hidden=true;return;}const results=searchStations(state.stations.features,input.value);list.replaceChildren(...results.map((f,i)=>{const li=el('li',friendlyStationName(f));li.id=`station-result-${i}`;li.setAttribute('role','option');li.dataset.stationId=f.properties.id;li.setAttribute('aria-selected',String(i===activeResult));li.append(el('small',f.properties.name));li.onmousedown=e=>{e.preventDefault();choose(f);input.value=friendlyStationName(f);list.hidden=true;};return li;}));activeResult=-1;list.hidden=!results.length;input.setAttribute('aria-expanded',String(!list.hidden));}
function bindUi():void { const metric=$('#metricSelect') as HTMLSelectElement,units=$('#unitSelect') as HTMLSelectElement,lang=$('#languageSelect') as HTMLSelectElement,range=$('#timeRange') as HTMLInputElement,input=$('#stationSearch') as HTMLInputElement,list=$('#searchResults');metric.onchange=()=>{state.metric=metric.value as Metric;if(isDeltaMetric(state.metric))stop();if(state.stations)state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id??null,state.metric,state.year);updateAll();};units.onchange=()=>{state.unit=units.value as TemperatureUnit;updateAll();};lang.onchange=()=>{state.language=lang.value as Language;updateAll();say(t(state.language,'language'));};range.oninput=()=>{state.year=state.years[Number(range.value)]??null;if(state.stations)state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id??null,state.metric,state.year);updateAll();};$('#playPauseBtn').onclick=()=>{if(state.playing)stop();else{state.playing=true;timer=setInterval(advance,900);updateTimeline();}};$('#resetMap').onclick=()=>boundaryLayer?map.fitBounds(boundaryLayer.getBounds(),{padding:[24,24]}):map.setView(center,9);input.oninput=renderResults;input.onfocus=renderResults;input.onkeydown=e=>{const results=[...list.querySelectorAll<HTMLLIElement>('[role=option]')];if(e.key==='Escape'){list.hidden=true;input.setAttribute('aria-expanded','false');}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();activeResult=Math.max(0,Math.min(results.length-1,activeResult+(e.key==='ArrowDown'?1:-1)));results.forEach((r,i)=>r.setAttribute('aria-selected',String(i===activeResult)));}if(e.key==='Enter'&&activeResult>=0){const id=results[activeResult]?.dataset.stationId,f=state.stations?.features.find(x=>x.properties.id===id);if(f){choose(f);input.value=friendlyStationName(f);list.hidden=true;}}};document.addEventListener('click',e=>{if(!($('.station-search').contains(e.target as Node)))list.hidden=true;});const dialog=$('#aboutDialog') as HTMLDialogElement;$('#aboutBtn').onclick=()=>dialog.showModal();$('#closeAbout').onclick=()=>dialog.close();dialog.addEventListener('close',()=>($('#aboutBtn') as HTMLButtonElement).focus());$('#shareBtn').onclick=async()=>{try{if(!navigator.clipboard)throw new Error();await navigator.clipboard.writeText(location.href);setStatus(t(state.language,'linkCopied'));}catch{setStatus(t(state.language,'copyFailed'),'warning');}};window.addEventListener('popstate',()=>{if(!state.stations)return;const p=parseUrlState(location.search,state.stations.features.map(f=>f.properties.id),state.years,{stationId:null,year:state.years.at(-1)??null,metric:'hot_days_32',unit:'F',language:'en'});state.year=p.year;state.metric=p.metric;state.unit=p.unit;state.language=p.language;state.selectedStation=selectedStation(state.stations.features,p.stationId,p.metric,p.year);updateAll(false);});}
async function initialize():Promise<void>{bindUi();setStatus(t(state.language,'loadingBoundary'));try{const b=parseBoundary(await fetchJson(boundaryUrl,'boundary'));boundaryLayer=L.geoJSON(b as GeoJSON.GeoJsonObject,{style:{color:'#17324d',weight:2,fill:false}}).addTo(map);map.fitBounds(boundaryLayer.getBounds(),{padding:[24,24]});}catch{setStatus(t(state.language,'boundaryFailed'),'warning');}setStatus(t(state.language,'loadingStations'));try{state.stations=parseStations(await fetchJson(stationsUrl,'station data'));state.years=collectAvailableYears(state.stations.features);const p=parseUrlState(location.search,state.stations.features.map(f=>f.properties.id),state.years,{stationId:null,year:state.years.at(-1)??null,metric:'hot_days_32',unit:'F',language:'en'});state.year=p.year;state.metric=p.metric;state.unit=p.unit;state.language=p.language;($('#languageSelect') as HTMLSelectElement).value=p.language;($('#unitSelect') as HTMLSelectElement).value=p.unit;state.selectedStation=selectedStation(state.stations.features,p.stationId,p.metric,p.year);stationLayer=createStationLayer().addTo(map);const range=$('#timeRange') as HTMLInputElement;range.min='0';range.max=String(state.years.length-1);range.value=String(state.years.indexOf(state.year!));updateAll();setStatus('');}catch(e){console.error(e);setStatus(t(state.language,'stationsFailed'),'error',true);}finally{setTimeout(()=>map.invalidateSize(),0);}}
void initialize();
