import 'leaflet/dist/leaflet.css';
import './styles/main.css';
import * as L from 'leaflet';
import { Chart, type ChartConfiguration } from 'chart.js/auto';
import boundaryUrl from '../data/pr_boundary.geojson?url';
import stationsUrl from '../data/stations_heatmetrics_all.geojson?url';
import { fetchJson, parseBoundary, parseStations } from './data/load-data';
import type { AppState, Metric, StationFeature, TemperatureUnit } from './types/heat-data';
import { collectAvailableYears, completenessLabel, coverage, daysInYear, formatCompleteness, isDeltaMetric, markerColor, metricDefinition, metricLabel, metricPercentile, metricValue, selectedStation, summaryFor, valueFor } from './utils/metrics';

const center: L.LatLngExpression = [18.2208, -66.5901];
const state: AppState = { year: null, metric: 'hot_days_32', unit: 'F', playing: false, years: [], stations: null, selectedStation: null };
const map = L.map('map', { center, zoom: 9, zoomControl: false });
L.control.zoom({ position: 'bottomright' }).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
let stationLayer: L.GeoJSON | null = null;
let boundaryLayer: L.GeoJSON | null = null;
let timer: ReturnType<typeof setInterval> | null = null;
let chart: Chart | null = null;

const $ = <T extends HTMLElement>(selector: string): T => document.querySelector<T>(selector)!;
function el<K extends keyof HTMLElementTagNameMap>(tag: K, text?: string): HTMLElementTagNameMap[K] { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; return node; }
function setStatus(message = '', kind = 'info'): void { const node = $('#appStatus'); node.textContent = message; node.className = `status ${kind}`; }
function displayMetric(): string { return metricLabel(state.metric, state.unit); }
function updateSelectLabels(): void { const select = $('#metricSelect') as HTMLSelectElement; [...select.options].forEach((option) => option.textContent = metricLabel(option.value as Metric, state.unit)); $('#metricDefinition').textContent = metricDefinition(state.metric, state.unit); }
function updateLegend(): void { const root = $('#legend'); root.replaceChildren(el('strong', `${displayMetric()} · days/year`)); const ranges: Array<[string, string]> = isDeltaMetric(state.metric) ? [['#2166ac','40 fewer or more'],['#91bfdb','1–39 fewer'],['#fee090','0–19 more'],['#d73027','20 more or more']] : [['#4575b4','Under 30'],['#91bfdb','30–59'],['#fee090','60–89'],['#fdae61','90–119'],['#d73027','120 or more']]; for (const [color,label] of ranges) { const row=el('span'); const dot=el('i'); dot.style.backgroundColor=color; row.append(dot,document.createTextNode(label)); root.append(row); } }
function updateTimeline(): void { const range = $('#timeRange') as HTMLInputElement; const delta = isDeltaMetric(state.metric); range.disabled = delta; $('#yearLabel').textContent = delta ? '2006–2025 vs 1961–1980' : state.year ?? '—'; const play = $('#playPauseBtn') as HTMLButtonElement; play.disabled = delta || !state.years.length; play.textContent = state.playing ? 'Pause' : 'Play'; const data = state.stations ? coverage(state.stations.features,state.metric,state.year) : {withData:0,total:0}; $('#coverageLabel').textContent = `${data.withData} of ${data.total} stations reporting`;
}
function destroyChart(): void { chart?.destroy(); chart = null; }
function updateChart(feature: StationFeature | null): void { destroyChart(); const canvas=$('#historyChart') as HTMLCanvasElement; const empty=$('#chartEmpty'); if (!feature || isDeltaMetric(state.metric)) { canvas.hidden=true; empty.hidden=false; empty.textContent='Historical chart is not available for period-change metrics.'; return; } const values=feature.properties.metrics[state.metric] ?? {}; const years=state.years.filter(y=>values[y] !== null && values[y] !== undefined); if (!years.length) { canvas.hidden=true; empty.hidden=false; empty.textContent='No historical data is available for this metric.'; return; } canvas.hidden=false; empty.hidden=true; const selected = state.year; const config: ChartConfiguration<'line',number[],string>={type:'line',data:{labels:years,datasets:[{label:displayMetric(),data:years.map(y=>values[y] ?? 0),borderColor:'#c7512a',backgroundColor:'rgba(199,81,42,.12)',fill:true,tension:.25,pointRadius:years.map(y=>y===selected?4:0),pointBackgroundColor:'#17324d',borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:(context)=>`${context.parsed.y} days`}}},scales:{x:{ticks:{maxTicksLimit:6,color:'#536271'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#536271'},title:{display:true,text:'Days per year'}}}}}; chart=new Chart(canvas,config); }
function card(label: string, value: string, detail?: string): HTMLElement { const node=el('article'); node.className='metric-card'; node.append(el('h3',label),el('strong',value)); if(detail) node.append(el('p',detail)); return node; }
function updatePanel(): void { const feature=state.selectedStation; const noData=$('#noData'); const cards=$('#metricCards'); const narrative=$('#narrative'); cards.replaceChildren(); narrative.replaceChildren(); if(!feature) { $('#stationName').textContent='No station selected'; $('#stationMeta').textContent='Choose a station marker with data for the selected year.'; noData.hidden=false; noData.textContent='No station has data for this selection.'; updateChart(null); return; }
  const p=feature.properties; const year=state.year; const selected=metricValue(feature,state.metric,year); $('#stationName').textContent=p.name; $('#stationMeta').textContent=`${year ?? 'Period comparison'} · records ${p.data_start_year ?? '—'}–${p.data_end_year ?? '—'}`; noData.hidden=selected !== null; noData.textContent=`No ${displayMetric().toLowerCase()} data is available for this station and year.`;
  const valid=valueFor(feature,'valid_days',year), complete=valueFor(feature,'completeness_pct',year); const hot=valueFor(feature,'hot_days_32',year), warm=valueFor(feature,'warm_nights_24',year); const hotPct=valueFor(feature,'hot_day_pct',year), warmPct=valueFor(feature,'warm_night_pct',year);
  cards.append(card('Hot days',hot === null?'—':String(Math.round(hot)),hotPct===null?'No percentage available':`${Math.round(hotPct)}% of observed days`),card('Warm nights',warm === null?'—':String(Math.round(warm)),warmPct===null?'No percentage available':`${Math.round(warmPct)}% of observed nights`),card('Longest hot streak',valueFor(feature,'longest_hot_streak',year) === null?'—':`${valueFor(feature,'longest_hot_streak',year)} days`,'Consecutive calendar days'),card('Longest warm-night streak',valueFor(feature,'longest_warm_night_streak',year) === null?'—':`${valueFor(feature,'longest_warm_night_streak',year)} nights`,'Consecutive calendar nights'),card('Data coverage',valid === null?'—':`${Math.round(valid)} of ${daysInYear(year)}`,complete === null?'Coverage unavailable':`${formatCompleteness(complete)} · ${completenessLabel(complete)}`));
  for(const line of summaryFor(feature,state.metric,year,state.unit)) narrative.append(el('p',line)); const percentile=metricPercentile(feature,state.metric,year); if(percentile !== null) cards.append(card('Historical context',`${Math.round(percentile)}th percentile`,'Among valid station years'));
  updateChart(feature);
}
function updateAll(): void { updateSelectLabels(); updateLegend(); updateTimeline(); updatePanel(); redraw(); }
function redraw(): void { if(!stationLayer || !state.stations) return; stationLayer.clearLayers(); stationLayer.addData(state.stations as GeoJSON.GeoJsonObject); }
function createStationLayer(): L.GeoJSON { return L.geoJSON(null,{filter:(raw)=>metricValue(raw as StationFeature,state.metric,state.year)!==null,pointToLayer:(raw,latlng)=>{const feature=raw as StationFeature; const selected=feature.properties.id===state.selectedStation?.properties.id; return L.circleMarker(latlng,{radius:selected?9:6,color:selected?'#17324d':'#fff',weight:selected?3:1.5,fillColor:markerColor(metricValue(feature,state.metric,state.year),state.metric),fillOpacity:.95});},onEachFeature:(raw,layer)=>{const feature=raw as StationFeature; layer.bindTooltip(`${feature.properties.name} · ${metricValue(feature,state.metric,state.year) ?? 'No data'} days`,{direction:'top'}); layer.on('click',()=>{state.selectedStation=feature; updateAll();}); layer.on('keydown',()=>{state.selectedStation=feature; updateAll();});}}); }
function stop(): void { if(timer) clearInterval(timer); timer=null; state.playing=false; updateTimeline(); }
function advance(): void { const index=state.years.indexOf(state.year ?? state.years[0]!); state.year=state.years[(index+1)%state.years.length] ?? null; ($('#timeRange') as HTMLInputElement).value=String(state.years.indexOf(state.year!)); if(state.stations) state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id ?? null,state.metric,state.year); updateAll(); }
function bindUi(): void { const metric=$('#metricSelect') as HTMLSelectElement; metric.onchange=()=>{state.metric=metric.value as Metric; if(isDeltaMetric(state.metric))stop(); if(state.stations) state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id ?? null,state.metric,state.year); updateAll();}; const units=$('#unitSelect') as HTMLSelectElement; units.onchange=()=>{state.unit=units.value as TemperatureUnit; updateAll();}; const range=$('#timeRange') as HTMLInputElement; range.oninput=()=>{state.year=state.years[Number(range.value)] ?? null; if(state.stations)state.selectedStation=selectedStation(state.stations.features,state.selectedStation?.properties.id ?? null,state.metric,state.year); updateAll();}; ($('#playPauseBtn') as HTMLButtonElement).onclick=()=>{if(state.playing)stop();else{state.playing=true;timer=setInterval(advance,900);updateTimeline();}}; ($('#resetMap') as HTMLButtonElement).onclick=()=>{if(boundaryLayer)map.fitBounds(boundaryLayer.getBounds(),{padding:[24,24]});else map.setView(center,9);}; ($('#aboutBtn') as HTMLButtonElement).onclick=()=>{const panel=$('#aboutData'); panel.hidden=!panel.hidden; ($('#aboutBtn') as HTMLButtonElement).setAttribute('aria-expanded',String(!panel.hidden));}; }
async function initialize(): Promise<void> { bindUi(); setStatus('Loading Puerto Rico boundary…'); try { const boundary=parseBoundary(await fetchJson(boundaryUrl,'the Puerto Rico boundary')); boundaryLayer=L.geoJSON(boundary as GeoJSON.GeoJsonObject,{style:{color:'#17324d',weight:2,fill:false}}).addTo(map); map.fitBounds(boundaryLayer.getBounds(),{padding:[24,24]}); setStatus(); } catch { setStatus('The Puerto Rico boundary could not be loaded. You can still use the map.','warning'); } setStatus('Loading station data…'); try { state.stations=parseStations(await fetchJson(stationsUrl,'station data')); state.years=collectAvailableYears(state.stations.features); state.year=state.years.at(-1) ?? null; if(!state.year)throw new Error('Station data contains no usable years.'); state.selectedStation=selectedStation(state.stations.features,null,state.metric,state.year); stationLayer=createStationLayer().addTo(map); const range=$('#timeRange') as HTMLInputElement; range.min='0';range.max=String(state.years.length-1);range.value=String(state.years.length-1); updateAll(); setStatus(); } catch { setStatus('Station data could not be loaded. Please try again later.','error'); } finally { setTimeout(()=>map.invalidateSize(),0); } }
void initialize();
