import 'leaflet/dist/leaflet.css';
import './styles/main.css';
import * as L from 'leaflet';
import { Chart, type ChartConfiguration } from 'chart.js/auto';
import boundaryUrl from '../data/pr_boundary.geojson?url';
import stationsUrl from '../data/stations_heatmetrics_all.geojson?url';
import { fetchJson, parseBoundary, parseStations } from './data/load-data';
import type { AppState, Metric, StationFeature, TemperatureUnit } from './types/heat-data';
import { collectAvailableYears, coverage, formatTemperature, isDeltaMetric, markerColor, metricLabel, metricValue } from './utils/metrics';

const center: L.LatLngExpression = [18.2208, -66.5901];
const state: AppState = { year: null, metric: 'hot_days_32', unit: 'F', playing: false, years: [], stations: null, selectedStation: null };
const map = L.map('map', { center, zoom: 8 });
const osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
L.control.scale({ metric: false, imperial: true }).addTo(map);
const layers = L.control.layers({ OpenStreetMap: osm }, {}, { collapsed: false }).addTo(map);
let stationLayer: L.GeoJSON | null = null;
let timer: ReturnType<typeof setInterval> | null = null;
const charts = new Map<HTMLCanvasElement, Chart>();

function element<K extends keyof HTMLElementTagNameMap>(name: K, text?: string): HTMLElementTagNameMap[K] { const node = document.createElement(name); if (text !== undefined) node.textContent = text; return node; }
function card(className: string): HTMLDivElement { const node = element('div'); node.className = className; L.DomEvent.disableClickPropagation(node); L.DomEvent.disableScrollPropagation(node); return node; }
const status = new Map<string, { message: string; kind: string }>();
function setStatus(key: string, message?: string, kind = 'info'): void { if (message) status.set(key, { message, kind }); else status.delete(key); const root = document.querySelector<HTMLDivElement>('#appStatus'); if (!root) return; root.replaceChildren(...[...status.values()].map(({ message: text, kind: type }) => { const p = element('p', text); p.className = type; return p; })); }

function values(): { withData: number; total: number } { return state.stations ? coverage(state.stations.features, state.metric, state.year) : { withData: 0, total: 0 }; }
function updateCoverage(): void { const target = document.querySelector('#coverageLabel'); if (!target) return; const current = values(); const scope = isDeltaMetric(state.metric) ? '2006-2025 minus 1961-1980' : `Year ${state.year ?? 'n/a'}`; target.textContent = `Coverage (${scope}): ${current.withData}/${current.total} stations (${current.total ? Math.round(current.withData / current.total * 100) : 0}%)`; setStatus('selection', current.withData || !state.stations ? undefined : `No station data is available for ${metricLabel(state.metric, state.unit)} in ${scope}.`, 'warning'); }
function updateLegend(): void { const root = document.querySelector('#legend'); if (!root) return; root.replaceChildren(element('h4', `${metricLabel(state.metric, state.unit)} (days per year)`)); const colors: Array<[string, string]> = isDeltaMetric(state.metric) ? [['#2166ac','≤ −40 days'],['#67a9cf','−39 to −20'],['#d1e5f0','−19 to −1'],['#fddbc7','0 to 19'],['#ef8a62','20 to 39'],['#b2182b','≥ 40 days']] : [['#4575b4','< 30 days'],['#91bfdb','30 – 59 days'],['#fee090','60 – 89 days'],['#fdae61','90 – 119 days'],['#d73027','≥ 120 days']]; for (const [color, label] of colors) { const row = element('div'); const swatch = element('span'); swatch.className = 'swatch'; swatch.style.background = color; row.append(swatch, document.createTextNode(label)); root.append(row); } }
function redraw(): void { if (!stationLayer || !state.stations) return; stationLayer.clearLayers(); stationLayer.addData(state.stations as GeoJSON.GeoJsonObject); updateCoverage(); }
function month(index: number | null | undefined): string { return index && index >= 1 && index <= 12 ? ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][index - 1] ?? `Month ${index}` : 'N/A'; }
function popup(feature: StationFeature): HTMLElement {
  const p = feature.properties; const root = element('div'); root.append(element('strong', p.name), element('br'), document.createTextNode(p.country), element('br'));
  const value = metricValue(feature, state.metric, state.year); root.append(document.createTextNode(isDeltaMetric(state.metric) ? 'Period: 2006–2025 minus 1961–1980' : `Year: ${state.year}`), element('br'), document.createTextNode(`${metricLabel(state.metric, state.unit)}: ${value ?? 'N/A'} days`));
  if (state.year) { for (const [key, label] of [['hot_days_32','Hot days'],['hot_days_35','Very hot days'],['warm_nights_24','Warm nights'],['oppressive_days','Oppressive days']] as const) { const v = p.metrics[key]?.[state.year]; if (v !== null && v !== undefined) root.append(element('br'), document.createTextNode(`${label}: ${v} days`)); }
  const max = p.metrics.hottest_month_tmax?.[state.year]; const min = p.metrics.hottest_month_tmin?.[state.year]; const idx = p.metrics.hottest_month_index?.[state.year]; if (max !== null && max !== undefined && min !== null && min !== undefined) root.append(element('br'), element('br'), element('em', `Hottest month: ${month(idx)}`), element('br'), document.createTextNode(`Avg max: ${formatTemperature(max, state.unit)}`), element('br'), document.createTextNode(`Avg min: ${formatTemperature(min, state.unit)}`)); }
  if (!isDeltaMetric(state.metric)) { const title = element('div', 'Trend across years'); title.className = 'chart-title'; const canvas = element('canvas'); canvas.height = 140; root.append(element('hr'), title, canvas); setTimeout(() => createChart(canvas, feature), 0); }
  return root;
}
function createChart(canvas: HTMLCanvasElement, feature: StationFeature): void { charts.get(canvas)?.destroy(); const data = feature.properties.metrics[state.metric] ?? {}; const labels = state.years.filter((year) => data[year] !== null && data[year] !== undefined); if (!labels.length) { canvas.replaceWith(element('div', 'No data to plot.')); return; } const config: ChartConfiguration<'line', number[], string> = { type: 'line', data: { labels, datasets: [{ label: metricLabel(state.metric, state.unit), data: labels.map((year) => data[year] ?? 0), borderColor: '#d73027', backgroundColor: 'rgba(215,48,39,.15)', borderWidth: 2, tension: .25, pointRadius: 0, fill: true }] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } }, scales: { x: { ticks: { maxTicksLimit: 6 } }, y: { beginAtZero: true } } } }; charts.set(canvas, new Chart(canvas, config)); }
function createStationLayer(): L.GeoJSON { return L.geoJSON(null, { filter: (raw) => metricValue(raw as StationFeature, state.metric, state.year) !== null, pointToLayer: (raw, latlng) => L.circleMarker(latlng, { radius: 6, color: '#333', weight: 1, fillColor: markerColor(metricValue(raw as StationFeature, state.metric, state.year), state.metric), fillOpacity: .9 }), onEachFeature: (raw, layer) => layer.bindPopup(() => popup(raw as StationFeature)) }); }
function control(position: L.ControlPosition, className: string, build: (root: HTMLDivElement) => void): void { const instance = new L.Control({ position }); instance.onAdd = () => { const root = card(className); build(root); return root; }; instance.addTo(map); }
function updateInputs(): void { const range = document.querySelector<HTMLInputElement>('#timeRange'); const label = document.querySelector('#timeLabel'); const play = document.querySelector<HTMLButtonElement>('#playPauseBtn'); if (range && label) { range.disabled = isDeltaMetric(state.metric); label.textContent = isDeltaMetric(state.metric) ? '2006–2025 minus 1961–1980' : state.year ?? 'Not available'; } if (play) { play.disabled = isDeltaMetric(state.metric) || !state.years.length; play.textContent = state.playing ? 'Pause' : 'Play'; } }
function stop(): void { if (timer) clearInterval(timer); timer = null; state.playing = false; updateInputs(); }
function advance(): void { const fallback = state.years[0]; if (!fallback) return; const index = state.years.indexOf(state.year ?? fallback); state.year = state.years[(index + 1) % state.years.length] ?? null; const range = document.querySelector<HTMLInputElement>('#timeRange'); if (range && state.year) range.value = String(state.years.indexOf(state.year)); redraw(); updateInputs(); }
control('topleft', 'app-status', (root) => { root.id = 'appStatus'; });
control('bottomright', 'legend', (root) => { root.id = 'legend'; updateLegend(); });
control('bottomleft', 'info-card', (root) => { root.append(element('strong', 'Caribbean Heat Stress Atlas — Puerto Rico'), element('br'), document.createTextNode('Daily max/min temperatures aggregated by year. Counts are per year at each station.')); });
control('topright', 'slider-wrap', (root) => { const head = element('div'); head.className = 'slider-header'; head.append(element('span', 'Time')); const button = element('button', 'Play'); button.id = 'playPauseBtn'; button.className = 'play-btn'; button.onclick = () => { if (state.playing) stop(); else { state.playing = true; timer = setInterval(advance, 900); updateInputs(); } }; const range = element('input') as HTMLInputElement; range.type = 'range'; range.id = 'timeRange'; range.oninput = () => { state.year = state.years[Number(range.value)] ?? null; redraw(); updateInputs(); }; const label = element('span', 'Not available'); label.id = 'timeLabel'; const coverageLabel = element('span', 'Coverage: not available'); coverageLabel.id = 'coverageLabel'; root.append(head, button, range, label, coverageLabel); });
control('topright', 'metric-wrap', (root) => { root.append(element('span', 'Metric')); const select = element('select'); for (const metric of ['hot_days_32','hot_days_35','warm_nights_24','oppressive_days','delta_hot_days_32','delta_warm_nights_24'] as Metric[]) { const option = element('option', metricLabel(metric, state.unit)); option.value = metric; select.append(option); } select.onchange = () => { state.metric = select.value as Metric; if (isDeltaMetric(state.metric)) stop(); [...select.options].forEach((o) => { o.textContent = metricLabel(o.value as Metric, state.unit); }); updateLegend(); redraw(); updateInputs(); }; root.append(select); });
control('topright', 'metric-wrap', (root) => { root.append(element('span', 'Temperature units')); const select = element('select'); (['F','C'] as TemperatureUnit[]).forEach((unit) => { const option = element('option', `°${unit} (${unit === 'F' ? 'Fahrenheit' : 'Celsius'})`); option.value = unit; select.append(option); }); select.onchange = () => { state.unit = select.value as TemperatureUnit; updateLegend(); }; root.append(select); });
control('topright', 'metric-wrap reset-wrap', (root) => { const button = element('button', 'Reset view'); button.onclick = () => map.setView(center, 8); root.append(button); });
async function initialize(): Promise<void> { setStatus('boundary', 'Loading Puerto Rico boundary…'); try { const boundary = parseBoundary(await fetchJson(boundaryUrl, 'the Puerto Rico boundary')); const layer = L.geoJSON(boundary as GeoJSON.GeoJsonObject, { style: { color: '#333', weight: 2, fill: false } }).addTo(map); layers.addOverlay(layer, 'Puerto Rico boundary'); map.fitBounds(layer.getBounds(), { padding: [12, 12] }); setStatus('boundary'); } catch (error) { setStatus('boundary', error instanceof Error ? error.message : 'Could not load boundary.', 'error'); }
  setStatus('stations', 'Loading station data…'); try { state.stations = parseStations(await fetchJson(stationsUrl, 'station data')); state.years = collectAvailableYears(state.stations.features); state.year = state.years[0] ?? null; if (!state.year) throw new Error('Station data contains no valid four-digit year keys.'); stationLayer = createStationLayer().addTo(map); layers.addOverlay(stationLayer, 'Temperature metrics (days per year)'); const range = document.querySelector<HTMLInputElement>('#timeRange'); if (range) { range.min = '0'; range.max = String(state.years.length - 1); range.value = '0'; } redraw(); updateInputs(); setStatus('stations'); } catch (error) { setStatus('stations', error instanceof Error ? error.message : 'Could not load station data.', 'error'); } finally { setTimeout(() => map.invalidateSize(), 0); } }
void initialize();
